### ISSUE TITLE
Callback onCancel not works properly

### ISSUE THREAD

**Issue by riccardocarrubba** [NexiPayments/sdk-android#2]
When the xPay.FrontOffice.pay method is called, if the user taps the device's Back button while the your webview (see screen attachment) is open, the onCancel callback is not triggered once the webview is closed.

![](https://cdn.discordapp.com/attachments/821329157845680148/1098974834974801981/Screenshot_20230421_160608.png)

Device and version:

Device: Android Simulators
OS version: Android 12
XPay-SDK: version 1.4.1

**Comment by NexiPayments** [comment]
Hello Riccardo,

We confirm that the "back" buttons on devices do not trigger the "onCancel" event of the SDK.

The "onCancel" event is returned when a customer clicks the appropriate payment cancellation buttons on the XPay checkout pages.

We kindly ask you to contact us at the email address [tech.ecommerce@nexi.it](mailto:tech.ecommerce@nexi.it) if you experience any issues or further doubts.
